### ISSUE TITLE
BUG: environment.yml fails to setup broken dependency obspy  (Ubuntu 18, Connectomemapper RC4)

### ISSUE THREAD

**Issue by jwirsich** [connectomicslab/connectomemapper3#105]
**Encountered issue**

Creating the conda environment for cmpbidasappmanager fails because of broken dependency:

```bash
conda env create -f environment.yml
```
```output
C compiler: gcc -pthread -B /home/jwirsich/miniconda3/envs/py37cmp-gui/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating build/temp.linux-x86_64-3.7/obspy
creating build/temp.linux-x86_64-3.7/obspy/io
creating build/temp.linux-x86_64-3.7/obspy/io/gse2
creating build/temp.linux-x86_64-3.7/obspy/io/gse2/src
creating build/temp.linux-x86_64-3.7/obspy/io/gse2/src/GSE_UTI
```

**OS:** Ubuntu 18.04
**CMP3 version:** v3.0.0-RC4

**Workaround**

Manually setup obspy (`conda install -c conda-forge obspy`) and uncomment it in environment.yml

**Comment by sebastientourbier** [comment]
I am closing this issue as this should have been fixed in release `v3.0.0` but feel free to reopen the issue if this happens again.

**Comment by jwirsich** [comment]
Still a problem with cmp3.1/python3.9 both on Ubuntu 18 and OS 12.6.1
